name: Linters

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8.16']

    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pdm sync -dG lint

      - name: Run lint
        run: pdm run ruff check

      - name: Run format check
        run: pdm run ruff format --check

      - name: Run mypy
        run: pdm run mypy src
